[package]
name = "word-lookup-rs"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "lookup_app"
path = "src/main.rs"

[[bin]]
name = "trigger_lookup"
path = "src/bin/trigger_lookup.rs"
